# python run.py +experiment=delivery-qlearning ++seed=1
# python run.py +experiment=delivery-qlearning ++seed=10
# python run.py +experiment=delivery-qlearning ++seed=13
# python run.py +experiment=delivery-qlearning ++seed=78
# python run.py +experiment=delivery-qlearning ++seed=84
# python run.py +experiment=delivery-qlearning ++seed=1006
# python run.py +experiment=delivery-qlearning ++seed=1007
# python run.py +experiment=delivery-qlearning ++seed=1008
# python run.py +experiment=delivery-qlearning ++seed=1009
# python run.py +experiment=delivery-qlearning ++seed=1010
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=1 
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=10
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=13
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=78
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=84
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=101
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=202
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=303
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=301
python run.py +experiment=delivery-qlearning ++fsa_name=task2 ++seed=103
# python run.py +experiment=office-qlearning ++seed=1006
# python run.py +experiment=office-qlearning ++seed=1007
# python run.py +experiment=office-qlearning ++seed=1008
# python run.py +experiment=office-qlearning ++seed=1009
# python run.py +experiment=office-qlearning ++seed=1010